// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'inspeccion.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_Inspeccion _$$_InspeccionFromJson(Map<String, dynamic> json) =>
    _$_Inspeccion(
      cotizacionId: json['cotizacion_id'] as String?,
      coordinacionId: json['coordinacion_id'] as String?,
      coordinacionCorrelativo: json['coordinacion_correlativo'] as String?,
      riesgoId: json['riesgo_id'] as String?,
      riesgoNombre: json['riesgo_nombre'] as String?,
      coordinadorId: json['coordinador_id'] as String?,
      coordinadorNombre: json['coordinador_nombre'] as String?,
      fechaSolicitud: json['fecha_solicitud'] as String?,
      entregaAlClienteFecha: json['entrega_al_cliente_fecha'] as String?,
      fechaEntrega: json['fecha_entrega'] as String?,
      solicitanteId: json['solicitante_id'] as String?,
      solicitanteNombre: json['solicitante_nombre'] as String?,
      contactoId: json['contacto_id'] as String?,
      contactoNombre: json['contacto_nombre'] as String?,
      clienteId: json['cliente_id'] as String?,
      clienteNombre: json['cliente_nombre'] as String?,
      servicioTipoId: json['servicio_tipo_id'] as String?,
      servicioTipoNombre: json['servicio_tipo_nombre'] as String?,
      tipoCambioId: json['tipo_cambio_id'] as String?,
      tipoCambioNombre: json['tipo_cambio_nombre'] as String?,
      tipoInspeccionId: json['tipo_inspeccion_id'] as String?,
      tipoInspeccionNombre: json['tipo_inspeccion_nombre'] as String?,
      modalidadId: json['modalidad_id'] as String?,
      modalidadNombre: json['modalidad_nombre'] as String?,
      inspeccionId: json['inspeccion_id'] as String?,
      peritoId: json['perito_id'] as String?,
      peritoNombre: json['perito_nombre'] as String?,
      inspeccionContacto: json['inspeccion_contacto'] as String?,
      inspeccionFecha: json['inspeccion_fecha'] as String?,
      inspeccionFechaNormal: json['inspeccion_fecha_normal'] as String?,
      inspeccionHora: json['inspeccion_hora'] as String?,
      inspeccionHoraTipo: json['inspeccion_hora_tipo'] as String?,
      distritoId: json['distrito_id'] as String?,
      distritoNombre: json['distrito_nombre'] as String?,
      provinciaId: json['provincia_id'] as String?,
      provinciaNombre: json['provincia_nombre'] as String?,
      departamentoId: json['departamento_id'] as String?,
      departamentoNombre: json['departamento_nombre'] as String?,
      inspeccionDireccion: json['inspeccion_direccion'] as String?,
      inspeccionLatitud: json['inspeccion_latitud'] as String?,
      inspeccionLongitud: json['inspeccion_longitud'] as String?,
      inspeccionObservacion: json['inspeccion_observacion'] as String?,
      estadoId: json['estado_id'] as String?,
      estadoNombre: json['estado_nombre'] as String?,
      infoStatus: json['info_status'] as String?,
      digitadorId: json['digitador_id'] as String?,
      digitadorNombre: json['digitador_nombre'] as String?,
      controlCalidadId: json['control_calidad_id'] as String?,
      controlCalidadNombre: json['control_calidad_nombre'] as String?,
    );

Map<String, dynamic> _$$_InspeccionToJson(_$_Inspeccion instance) =>
    <String, dynamic>{
      'cotizacion_id': instance.cotizacionId,
      'coordinacion_id': instance.coordinacionId,
      'coordinacion_correlativo': instance.coordinacionCorrelativo,
      'riesgo_id': instance.riesgoId,
      'riesgo_nombre': instance.riesgoNombre,
      'coordinador_id': instance.coordinadorId,
      'coordinador_nombre': instance.coordinadorNombre,
      'fecha_solicitud': instance.fechaSolicitud,
      'entrega_al_cliente_fecha': instance.entregaAlClienteFecha,
      'fecha_entrega': instance.fechaEntrega,
      'solicitante_id': instance.solicitanteId,
      'solicitante_nombre': instance.solicitanteNombre,
      'contacto_id': instance.contactoId,
      'contacto_nombre': instance.contactoNombre,
      'cliente_id': instance.clienteId,
      'cliente_nombre': instance.clienteNombre,
      'servicio_tipo_id': instance.servicioTipoId,
      'servicio_tipo_nombre': instance.servicioTipoNombre,
      'tipo_cambio_id': instance.tipoCambioId,
      'tipo_cambio_nombre': instance.tipoCambioNombre,
      'tipo_inspeccion_id': instance.tipoInspeccionId,
      'tipo_inspeccion_nombre': instance.tipoInspeccionNombre,
      'modalidad_id': instance.modalidadId,
      'modalidad_nombre': instance.modalidadNombre,
      'inspeccion_id': instance.inspeccionId,
      'perito_id': instance.peritoId,
      'perito_nombre': instance.peritoNombre,
      'inspeccion_contacto': instance.inspeccionContacto,
      'inspeccion_fecha': instance.inspeccionFecha,
      'inspeccion_fecha_normal': instance.inspeccionFechaNormal,
      'inspeccion_hora': instance.inspeccionHora,
      'inspeccion_hora_tipo': instance.inspeccionHoraTipo,
      'distrito_id': instance.distritoId,
      'distrito_nombre': instance.distritoNombre,
      'provincia_id': instance.provinciaId,
      'provincia_nombre': instance.provinciaNombre,
      'departamento_id': instance.departamentoId,
      'departamento_nombre': instance.departamentoNombre,
      'inspeccion_direccion': instance.inspeccionDireccion,
      'inspeccion_latitud': instance.inspeccionLatitud,
      'inspeccion_longitud': instance.inspeccionLongitud,
      'inspeccion_observacion': instance.inspeccionObservacion,
      'estado_id': instance.estadoId,
      'estado_nombre': instance.estadoNombre,
      'info_status': instance.infoStatus,
      'digitador_id': instance.digitadorId,
      'digitador_nombre': instance.digitadorNombre,
      'control_calidad_id': instance.controlCalidadId,
      'control_calidad_nombre': instance.controlCalidadNombre,
    };
